export function buildExplanation(input: {
  kind: string;
  evidence?: string[];
  attribution?: string[];
  reasoning?: string[];
  summary?: string;
}): {
  evidence: string[];
  attribution: string[];
  reasoning: string[];
  summary: string;
} {
  return {
    evidence: input.evidence ?? [`${input.kind}_stub_evidence`],
    attribution: input.attribution ?? [`model:stub`, `capability:${input.kind}`],
    reasoning: input.reasoning ?? [`Deterministic stub reasoning for ${input.kind}`],
    summary: input.summary ?? `Advisory ${input.kind} result generated by stub pipeline.`,
  };
}
